version: '3'     

services:                                                             
  jupyterlab1:                                                       
    build: jupyterlab1                                                
    image: hannahnw124-jlab-gromacs                                   
    container_name: jupyterlab1                                       
    volumes:                                                          
      - /var/run/docker.sock:/var/run/docker.sock                     
      - /mnt/nfshome:/nfshome                                        
      - hubdata:/srv/jupyterhub                                       
    ports:                                                            
      - "8888:8888"                                                                                                                                                        
    restart: on-failure                                               
  
  jupyterlab2:
    build: jupyterlab2
    image: hannahnw124-jlab-gromacs
    container_name: jupyterlab2
     volumes:                                                          
      - /var/run/docker.sock:/var/run/docker.sock                     
      - /mnt/nfshome:/nfshome                                        
      - hubdata:/srv/jupyterhub  
    restart: on-failure

volumes:                                                              
  hubdata:                                                            
