version: '3'     

services:                                                             
  jupyterlab1:                                                       
    build: jupyterlab1                                                
    image: hannahnw124-jlab-gromacs                                   
    container_name: jupyterlab1                                       
    volumes:                                                          
      - //c/Users/Williams/Desktop/Docker:/home/jovyan/work                                     
    ports:                                                            
      - "8888:8888"                                                                                                                                                        
    restart: on-failure                                               
  
  jupyterlab2:
    build: jupyterlab2
    image: hannahnw124-jlab-gromacs
    container_name: jupyterlab2
     volumes:                                                          
      - //c/Users/Williams/Desktop/Docker:/home/jovyan/work
    restart: on-failure                                                           
